[pytest]
pythonpath = . modules
markers =
    e2e: mark test as end-to-end (slow)
    slow: mark test as slow
    integration: mark test as integration test
    unit: mark test as unit test
    compatibility: mark test as compatibility test
    stress: mark test as stress test
    system: mark test as system test
filterwarnings =
    ignore::DeprecationWarning
    ignore::PendingDeprecationWarning
    ignore::FutureWarning
