"""
Struct Definition Generator
Generates ctypes Structure classes with padding and validation logic.
"""

from typing import Dict, Any, List

class StructDefinitionGenerator:
    """
    Produces Python ctypes Structure definitions from contract/IR data.
    """
    
    TYPE_MAP = {
        "primitive:int8": "ctypes.c_int8",
        "primitive:int16": "ctypes.c_int16",
        "primitive:int32": "ctypes.c_int32",
        "primitive:int64": "ctypes.c_int64",
        "primitive:uint8": "ctypes.c_uint8",
        "primitive:uint16": "ctypes.c_uint16",
        "primitive:uint32": "ctypes.c_uint32",
        "primitive:uint64": "ctypes.c_uint64",
        "primitive:float": "ctypes.c_float",
        "primitive:double": "ctypes.c_double",
        "primitive:char": "ctypes.c_char",
        "primitive:void": "None",
        "pointer:primitive:void": "ctypes.c_void_p",
        "pointer:primitive:char": "ctypes.c_char_p"
    }
    
    def generate_struct_module(self, library_name: str, structs: List[Dict[str, Any]], ir: Dict[str, Any]) -> str:
        """Generates the full structs module."""
        lines = [
            f'"""',
            f'Generated struct definitions for {library_name}.',
            f'',
            f'Auto-generated by Polyglot FFI Contract Verifier.',
            f'DO NOT EDIT MANUALLY.',
            f'"""',
            f'',
            f'import ctypes',
            f'from . import {library_name}_exceptions as exceptions',
            f''
        ]
        
        # We need to sort structs by dependency if they nest, 
        # but for v1.0 we assume flat or pre-ordered
        for s in structs:
            lines.append(self.generate_struct_class(s))
            lines.append("")
            
        return "\n".join(lines)

    def generate_struct_class(self, s: Dict[str, Any]) -> str:
        name = s["struct_name"]
        size = s["size_bytes"]
        align = s["alignment_bytes"]
        
        fields = s.get("field_contracts", [])
        
        class_lines = [
            f"class {name}(ctypes.Structure):",
            f'    """',
            f'    Native struct \'{name}\' binding.',
            f'    Size: {size} bytes',
            f'    Alignment: {align} bytes',
            f'    """',
            f'    _fields_ = ['
        ]
        
        for f in fields:
            f_name = f["field_name"]
            f_type = f["type_id"]
            ctypes_type = self._map_type(f_type)
            class_lines.append(f'        ("{f_name}", {ctypes_type}),')
            
        class_lines.extend([
            f'    ]',
            f'',
            f'    def __init__(self, **kwargs):',
            f'        super().__init__()',
            f'        actual_size = ctypes.sizeof(self)',
            f'        if actual_size != {size}:',
            f'            raise exceptions.LayoutMismatchError(',
            f'                "struct:{name}",',
            f'                f"Struct {name} has size {{actual_size}} bytes, expected {size} bytes"',
            f'            )',
            f'        for key, value in kwargs.items():',
            f'            if not hasattr(self, key):',
            f'                raise ValueError(f"Unknown field: {{key}}")',
            f'            setattr(self, key, value)',
            f''
        ])
        
        return "\n".join(class_lines)

    def _map_type(self, type_id: str) -> str:
        if type_id in self.TYPE_MAP:
            return self.TYPE_MAP[type_id]
            
        if type_id.startswith("padding:"):
            size = type_id.split(":")[-1]
            return f"ctypes.c_byte * {size}"
            
        if type_id.startswith("pointer:struct:"):
            s_name = type_id.split(":")[-1]
            return f"ctypes.POINTER({s_name})"
            
        if type_id.startswith("struct:"):
            return type_id.split(":")[-1]
            
        if type_id.startswith("pointer:primitive:"):
             base = type_id.replace("pointer:", "")
             if base in self.TYPE_MAP:
                 return f"ctypes.POINTER({self.TYPE_MAP[base]})"
                 
        return "ctypes.c_void_p" # Fallback
