"""
Markdown Report Generator
Produces FFI verification reports in Markdown format.
"""

import json
from datetime import datetime
from typing import Any, Dict, List

class MarkdownReportGenerator:
    """
    Generates structured Markdown reports for version control and plain text review.
    """

    def generate(self, diagnostics: Dict[str, Any], execution_log: Dict[str, Any], contract: Dict[str, Any], context: Any) -> str:
        summary = diagnostics.get("summary", {})
        violations = diagnostics.get("violations", [])
        
        timestamp = datetime.fromisoformat(context.provenance.creation_timestamp.replace('Z', '+00:00')).strftime('%Y-%m-%d %H:%M:%S')
        status_icon = "❌" if summary.get("severity_counts", {}).get("critical", 0) > 0 else "✅"
        status_text = "FAILED" if summary.get("severity_counts", {}).get("critical", 0) > 0 else "PASSED"

        md = [
            f"# FFI Contract Verification Report",
            f"",
            f"**Library:** `{context.native_library.library_path}`  ",
            f"**Date:** {timestamp}  ",
            f"**Status:** {status_icon} {status_text}",
            f"",
            f"---",
            f"",
            f"## Executive Summary",
            f"",
            f"| Metric | Value |",
            f"|--------|-------|",
            f"| Critical Violations | {summary.get('severity_counts', {}).get('critical', 0)} |",
            f"| High Severity | {summary.get('severity_counts', {}).get('high', 0)} |",
            f"| Medium Severity | {summary.get('severity_counts', {}).get('medium', 0)} |",
            f"| Pass Rate | {summary.get('pass_rate', 0):.1f}% |",
            f"",
            f"**Overall Status:** Verification {status_text}",
            f"",
            f"{'Critical violations detected. Deployment blocked.' if status_text == 'FAILED' else 'Contract verification passed. Ready for deployment.'}",
            f"",
            f"---",
            f"",
            f"## Test Results",
            f"",
            f"| Measurement | Count |",
            f"|-------------|-------|",
            f"| Total Tests | {len(execution_log.get('test_results', []))} |",
            f"| Passed | {sum(1 for r in execution_log.get('test_results', []) if r.get('status') == 'passed')} |",
            f"| Failed | {len(execution_log.get('test_results', [])) - sum(1 for r in execution_log.get('test_results', []) if r.get('status') == 'passed')} |",
            f"",
            f"---",
            f""
        ]

        # Violations
        if violations:
            md.append("## Detailed Violations")
            md.append("")
            
            # Sort critical first
            sorted_violations = sorted(violations, key=lambda x: {"critical": 0, "high": 1, "medium": 2, "low": 3}.get(x.get("severity"), 9))
            
            for v in sorted_violations:
                md.append(f"### [{v.get('violation_id', 'v???')}] {v.get('category')} in `{v.get('function_name')}()`")
                md.append("")
                md.append(f"**Severity:** {v.get('severity', '').upper()}  ")
                md.append(f"**Constraint:** `{v.get('constraint_id')}`  ")
                md.append(f"**Affected Tests:** {len(v.get('affected_tests', []))} failures")
                md.append("")
                md.append("#### Description")
                md.append(v.get("description", ""))
                md.append("")
                md.append("#### Impact")
                md.append(f"- {v.get('impact')}")
                md.append(f"- **Exploitability:** {v.get('exploitability')}")
                md.append("")
                md.append("#### Remediation")
                md.append(f"**{v.get('remediation', {}).get('short_description')}**")
                for step in v.get("remediation", {}).get("detailed_steps", []):
                    md.append(f"- {step}")
                md.append("")
        
        # Verified
        md.append("## Verified Constraints")
        md.append("")
        violated_cids = {v.get("constraint_id") for v in violations}
        all_constraints = []
        if "functions" in contract:
            for f_name, f_spec in contract["functions"].items():
                for c in f_spec.get("constraints", []):
                    all_constraints.append(c.get("id"))
        
        verified = [cid for cid in all_constraints if cid not in violated_cids]
        for cid in verified:
            md.append(f"- ✓ `{cid}`")
        if not verified:
            md.append("None.")
        md.append("")

        # Technical
        md.append("## Technical Details")
        md.append("")
        md.append(f"- **Execution ID:** `{context.provenance.execution_id}`")
        md.append(f"- **Platform:** {context.platform.os_name} {context.platform.os_version}")
        md.append(f"- **Tool Version:** {context.provenance.tool_version}")
        md.append("")
        md.append("---")
        md.append(f"Generated by Polyglot FFI Contract Verifier")

        return "\n".join(md)
