"""
Generated exception classes for test_library.

Auto-generated by Polyglot FFI Contract Verifier.
DO NOT EDIT MANUALLY.
"""

class FFIContractViolation(Exception):
    """
    Base class for all FFI contract violations.
    
    Attributes:
        constraint_id: Unique identifier for the violated constraint
        message: Human-readable description of the violation
    """
    def __init__(self, constraint_id, message):
        self.constraint_id = constraint_id
        self.message = message
        super().__init__(f"[{constraint_id}] {message}")


class NullPointerViolation(FFIContractViolation):
    """
    Raised when a pointer that must not be NULL is actually NULL.
    
    Contract constraint type: non_null
    """
    pass


class BufferSizeViolation(FFIContractViolation):
    """
    Raised when a buffer size constraint is violated.
    
    Contract constraint type: buffer_size
    """
    pass


class LayoutMismatchError(FFIContractViolation):
    """
    Raised when a struct layout doesn't match the contract specification.
    
    Contract constraint type: struct_layout
    """
    pass


class OwnershipViolation(FFIContractViolation):
    """
    Raised when memory ownership rules are violated.
    
    Contract constraint types: borrowed, transferred
    """
    pass


class ReturnValueViolation(FFIContractViolation):
    """
    Raised when a return value doesn't satisfy post-conditions.
    
    Contract constraint type: error_code, return_value_range
    """
    pass
